[package]
name = "blake3"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
# Like SSE4.1 and AVX2, the AVX-512 implementation uses dynamic feature
# detection, so a binary with "c_avx512" on is still cross-platform.
c_avx512 = []
# The NEON implementation does not use dynamic feature detection. If "c_neon"
# is on, NEON support is assumed. Note that AArch64 always supports NEON, but
# support on ARMv7 varies. (See also comments about ARMv7 in build.rs. You'll
# probably need to uncomment some flags there to convince the C compiler to
# turn on NEON support.)
c_neon = []
std = []

[dependencies]
arrayref = "0.3.5"
arrayvec = { version = "0.5.1", default-features = false, features = ["array-sizes-33-128"] }
constant_time_eq = "0.1.4"
rayon = { version = "1.2.1", optional = true }
cfg-if = "0.1.10"

[dev-dependencies]
page_size = "0.4.1"
rand = "0.7.2"
rand_chacha = "0.2.1"
reference_impl = { path = "./reference_impl" }

[build-dependencies]
cc = "1.0.48"
